DROP DATABASE IF EXISTS projectynov;
-- MySQL Script generated by MySQL Workbench
-- Fri Jun 29 17:31:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema projectynov
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectynov
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `projectynov` DEFAULT CHARACTER
SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `projectynov`;
-- -----------------------------------------------------
-- Table `projectynov`.`profile`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `projectynov`.`profile`
( 
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR
(255) NULL,
  `first_name` VARCHAR
(255) NULL,
  `year` VARCHAR
(255) NULL,
  `campus` VARCHAR
(255) NULL,
  `password` VARCHAR
(255) NULL,
  `email` VARCHAR
(255) NULL,
  `skill` VARCHAR
(255) NULL,
  `created_at` TIMESTAMP
(4) NULL,
  `updated_at` TIMESTAMP
(4) NULL,
  PRIMARY KEY
(`id`)
)
ENGINE = InnoDB;
CREATE UNIQUE INDEX `email_UNIQUE` ON `projectynov`.`profile`
(`email` ASC);
CREATE UNIQUE INDEX `skill_UNIQUE` ON `projectynov`.`profile`
(`skill` ASC);
-- -----------------------------------------------------
-- Table `projectynov`.`project`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `projectynov`.`project`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR
(255) NULL,
  `deadline_project` TIMESTAMP
(4) NULL,
  `deadline_application` TIMESTAMP
(4) NULL,
  `description` VARCHAR
(255) NULL,
  `state` TINYINT NULL,
  `created_at` TIMESTAMP
(4) NULL,
  `updated` TIMESTAMP
(4) NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY
(`id`, `profile_id`),
  CONSTRAINT `fk_project_profile`
    FOREIGN KEY
(`profile_id`)
    REFERENCES `projectynov`.`profile`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_project_profile_idx` ON `projectynov`.`project`
(`profile_id` ASC);
SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;